### ISSUE TITLE
Pre-hydration of Additives

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/LabDatabase_WorkItems#28]
There needs to be a pre-hydration property added to each additive on the iteration tab, this is a Yes/No value.  
- Should default to No
- This value should also show on the Experimental section. (NoteL: Experimental also has the Base field, we will require both there)
- NEED to talk to Jason about how these values come from the JSON request

**Comment by rantifamilusi** [comment]
@cgaine , Please explain `Experimental also has the Base field, we will require both there` . How does it impact the pre-hydration flag for each iteration?
