### ISSUE TITLE
Write MTS# to Chart Creator

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/LabDatabase_WorkItems#30]
The MTS number should be written to the Chart Creator.  When a Login number exists for a Cement of Source (Field or Bulk Plant), The application should pull the MTS number from the indicated Sample Login entry.  When the Chart Creator is downloaded, the MTS number should be written to the correct location in the chart Creator.

**Comment by rantifamilusi** [comment]
@cgaine , please provide sample chart creator files to identify the MTS number location. Please provide for all impacted chart creator.

**Comment by cgaine** [comment]
@rantifamilusi here are the current Chart Creator Templates
[Chart Creator Templates.zip](https://github.com/Sanjel-Energy-Services/LabDatabase_WorkItems/files/3989210/Chart.Creator.Templates.zip)

Each of them (except CWCreator) has an MTS field on the data tab where the MTS number can be written.
