### ISSUE TITLE
VISWEEP DM IS not available as a blend in lab database

### ISSUE THREAD

**Issue by siremonger** [Sanjel-Energy-Services/LabDatabase_WorkItems#57]
I was wanting to upload some data on our spacer VISWEEP DM IS into the lab database that was not associated with an existing test request. However, when manually creating a request, I was not given the option to select VISWEEP DM IS in the Blend Base. This can be seen in the snip below.

Any thoughts on what could cause this? The Eng. team can submit test requests for VISWEEP DM IS but for some reason they cannot be manually added.

**Comment by cgaine** [comment]
Updated the Blends View to include Preflush/Spacer/Displacement
